# -*- coding: utf-8 -*-
"""x^y,cube,square

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IqZoWtjLDYZx9A7uRBSTolkiHzF6Yqmx
"""

#x^y
x = float(input("Enter the number here x:"))
y = float(input("Enter the number here y:"))
n1 = x ** y
print("The x^y number is ",n1)

## square

num = float(input("Enter the number here :"))
sr1 = num**2
print("The square number is",sr1)

##cube
num = float(input("enter the number here :"))
cube = num**3
print("The cube number is ",cube)